### ISSUE TITLE
Events page show empty columns for first and last seen

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#109]
Running today

![screen shot 2016-02-29 at 4 35 12 pm](https://cloud.githubusercontent.com/assets/477100/13399221/82087528-df02-11e5-85d0-0fe4ebdf4357.png)

Notice how they are empty. But if you run oc get events then the events has times in 20m etc
```
IRSTSEEN   LASTSEEN   COUNT     NAME                                 KIND                    SUBOBJECT                                TYPE      REASON                  SOURCE                           MESSAGE
20m         20m        1         172.28.128.4                         Node                                                             Normal    Starting                {kube-proxy 172.28.128.4}        Starting kube-proxy.
20m         20m        1         172.28.128.4                         Node
```

**Comment by davsclaus** [comment]
Also the sorting do not work, but I think that is a known issue in the hawtio-ui project

**Comment by gashcrumb** [comment]
Wonder if it could be from removing sugarjs, might be worth checking the js console...

**Comment by gashcrumb** [comment]
K, sure enough those columns were using .relativeTime() from sugarjs.  I've added a filter so instead in templates we can do `foo.someDate | relativeTime`
