### ISSUE TITLE
There's no error or redirect, when the console session times out

### ISSUE THREAD

**Issue by myfear** [fabric8io/fabric8-console#11]
Using the console and having it open until the http-session times out, doesn't lead to a logout or error message. I can still change values (e.g. for pods) and just don't get any feedback as a user. 
A page refresh finally redirects me to the login screen.
Tested v1.0.25

**Comment by gashcrumb** [comment]
This should be sorted once we get the console using hawtio-oauth 2.0.27

**Comment by gashcrumb** [comment]
Actually 2.0.28

**Comment by davsclaus** [comment]
Assume its fixed now
