### ISSUE TITLE
Add a button in the log viewer to make it follow log

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#110]
I am showing the logs from a pod where it logs every 2nd second. And I scroll to the bottom and see Hello Riga 105. And after a while there is many more logs. And I have to scroll down again.

Would be nice with a "auto scroll" button or what is the term to use.

![screen shot 2016-02-29 at 4 56 54 pm](https://cloud.githubusercontent.com/assets/477100/13399889/a859a71c-df05-11e5-921f-bda6e5a81953.png)

**Comment by gashcrumb** [comment]
Hmm, it should be auto-scrolling initially, if you move the scrollbar it'll stop and then you have to scroll it back down to the bottom for the auto-scrolling to start working again.

**Comment by gashcrumb** [comment]
Wonder, maybe I messed that up when I made the window resize-able and movable, checking now...

**Comment by gashcrumb** [comment]
Oh, looks like you're running an older version actually, the latest code has a maximize button in the title bar.

**Comment by davsclaus** [comment]
Yeah I am not a hipster, running todays fabric8-installer vagrant image. Well I can wait for the next release to try again

**Comment by davsclaus** [comment]
I wonder if we can have an icon to indicate if auto scrolling is active or not. Because I have tried yesterday with latest release and it does not appear to be working, eg if you move the scrollback then it cannot seem to get auto scrolling again.

**Comment by gashcrumb** [comment]
Lemme maybe see if I can add a button to turn the scrolling back on, am testing it here using the forge pod (it logs pretty much all requests) and again it works fine for me, but of course on Macs the scrollbar is hidden unlike on Windows, so it's pretty hard to see if you're looking at the bottom of the log or not.
