### ISSUE TITLE
Deployed column in apps overview in table mode

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#120]
What does that deployed column mean? Notice its empty for all of them.

To see it, click that button on the top right corner to switch to table mode.

![screen shot 2016-03-11 at 3 42 33 pm](https://cloud.githubusercontent.com/assets/477100/13705205/0cef590e-e7a0-11e5-8dab-cfc3bf97a361.png)

**Comment by gashcrumb** [comment]
Just found it, it's supposed to be a relative time since that app's been deployed, doing a bit of cleanup so will fix it too...
