### ISSUE TITLE
Update README on old docker fabric8/hawtio image to show it has been replaced

### ISSUE THREAD

**Issue by jdcockrill** [fabric8io/fabric8-console#13]
From an IRC discussion with @jimmidyson . 

The old docker image for this project is fabric8/hawtio. This has been replaced by fabric8/fabric8-console.

fabric8/hawtio should have its README updated to show that it has been replaced and direct users to the replacement image.

Ideally some additional README content should be added to the new image as well.

**Comment by davsclaus** [comment]
The fabric8/hawtio git repo has been removed
