### ISSUE TITLE
Errors when trying to run cd-pipeline app

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8-console#134]
When trying to run the cd-pipeline app I get a couple of yellow crosses on the jenkins & jenkins-jnlp 

Started from a clean environment using the vagrant approach on mac.

kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'routes "jenkins" already exists'
reason: AlreadyExists
details:
  name: jenkins
  kind: routes
code: 409

kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'services "jenkins-jnlp" already exists'
reason: AlreadyExists
details:
  name: jenkins-jnlp
  kind: services
code: 409

This caused problems later when trying to create apps

**Comment by philpodlevsky** [comment]
I encountered the same issue and found this existing issue on the issue tracker: https://github.com/fabric8io/fabric8/issues/5964 

Workaround is to run the CD pipeline app a second time then the components with yellow Xs and the Jenkins Service will install correctly.

**Comment by davsclaus** [comment]
Try again with latest as a lot has happened

**Comment by stevef1uk** [comment]
Agreed fixed areas ago
