### ISSUE TITLE
Deployment view 

### ISSUE THREAD

**Issue by saardemri** [fabric8io/fabric8-console#143]
Is there a plan to show the deployments view and replication sets ?

**Comment by jstrachan** [comment]
yes, that'd be great!

**Comment by jstrachan** [comment]
the current Project Dashboard / App Dashboards shows rolling upgrades and the effects of Deployments; though it doesn't yet show ReplicaSets. We should really unify both ReplicaSets and ReplicationControllers into the same logical entity in the UI for easier visualisation

**Comment by jstrachan** [comment]
the console now shows Deployments (which show Deployments on kubernetes or DeploymentConfigs on OpenShift) along with Replicas (which are ReplicaSets on kubernetes and ReplicationControllers on OpenShift)
