### ISSUE TITLE
add better getting started UX for the console running before users run `cd-pipeline`

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-console#178]
Right now users have to know to:

* pick/create a team
* navigate to it
* go to `Runtime` view
* find the `Run...` button and click it
* pick the `cd-pipeline` app and run it
* then wait for it to startup then when its up navigate back the team page again
* now click `Create Application`

I wonder if we can do better? e.g. can we prompt users to run the `cd-pipeline` app if its not running on the `Create Application` page on a Team page?

**Comment by gashcrumb** [comment]
Which 'create' button did you use?  If you use 'Create Team' at the top-right, it basically goes through those steps...

**Comment by jstrachan** [comment]
Ah! Didn't think of creating a new team; just selected default! Lemme try that then....

**Comment by gashcrumb** [comment]
Yeah, do 'create team' and then use the existing 'default' namespace...

Granted, a bit more guidance is needed for sure...

**Comment by jstrachan** [comment]
AWESOME! I'd not even noticed that was there!!! :) 

I wonder if on the home page if folks had not created a team yet and we know there's no fabric8-environment / cd-pipeline running, we give folks a hint to get started? 

Kinda a recommendation line on the home page to try Create Team first? (Maybe we make Create Namespace non-primary too so its not bright?)

**Comment by gashcrumb** [comment]
yeah, good call.  Or even a 'get started' arrow that points you to that button :-)

**Comment by jstrachan** [comment]
Yeah!!! Great work though!

Also I noticed the page 2 said "waiting to apply configuration" when it was kinda ready - that maybe needs a tidy up a little. But awesome thanks!

**Comment by gashcrumb** [comment]
Actually yeah, we should maybe make that 'create team' button way more prominent when there's no teams, like we do when there's no projects etc.

**Comment by jstrachan** [comment]
Just tried the UI with Create Team; the issue is that the gofabric8 installer creates the fabric8 ServiceAccount and sets up the SCC so that jenkins can run hostPath privilidged containers. So if you do Create Team and use a different team to where fabric8 was installed, running CD Pipeline fails!

So I think our getting started experience should try encourage users to run the CD Pipeline in the namespace where we installed the fabric8 console.

I'm thinking that the gofabric8 install process should maybe mark the namespace you install fabric8 in as a Team to start with; so users don't have to Create a team; they are just encouraged to pick the default team.

Then when they are in the default team, the Dashboard shows a `Create Application` link. When we know that there's no `cd-pipeline` running, thats the page we should add the 'Please run CD Pipeline to be able to create Applications` UI?

**Comment by gashcrumb** [comment]
Be nice if the console was able to also handle setting up that SCC in some way, otherwise 'create team' isn't really going to be much good.  I wonder if we could embed some of the gofabric8 functionality into fabric8-console's backend?

**Comment by jstrachan** [comment]
Yeah; though that could be quite hard for security; it'd mean the console would have to run as cluster-admin which might scare folks. It might be better if we just get the gofabric8 to install the cd-pipeline by default maybe? Though it'd be awesome if folks could just run a simple console then install cd-pipeline; its just kinda complex with security...

**Comment by gashcrumb** [comment]
Ah gotcha, yeah we don't want to require running with cluster-admin.  I guess we could instead have the 'create team' stuff just let you know the right gofabric8 command to run, i.e. 'as an admin run this command to get cd-pipeline going'.  I guess though this kinda renders the create team wizard a bit pointless for the most part :-)

**Comment by jstrachan** [comment]
Yeah! I'm wondering if gofabric8 should 'create the team' then the UI should prompt for the CD Pipeline app when you are in the gofabric8-created-team view?

**Comment by gashcrumb** [comment]
yeah, in a way we kinda do that, as the dashboard prompts you to create a project (actually most of the team pages do) which in turn prompts you to install cd-pipeline.

Maybe cd-pipeline should kinda just get installed by default for whatever the default team is, then you can just go into your team and go right to creating a project which might be nicer.

**Comment by jstrachan** [comment]
Yeah - I'm definitely leaning toward installing cd-pipeline by default unless you opt out!

**Comment by gashcrumb** [comment]
Yeah, I think about it this way, you can't use over half of the console without cd-pipeline and projects, so it should be something out of the box really before you even go to the console I think.

**Comment by rawlingsj** [comment]
yeah - we could always provide a flag to install a minimal setup which avoids the cd-pipeline

**Comment by jstrachan** [comment]
Yeah! I'm thinking we should just switch gofabric8 so that --app=cd-pipeline by default; then folks can opt out of it if they want by supplying --app=foo or --no-app or something

**Comment by jstrachan** [comment]
There's a current issue with using `--app=cd-pipeline` right now in that the secret namespace + gogsadmin secret doesn't get generated (which is a bug in gofabric8 that needs fixing).

Will get onto the gofabric8 changes next week if noone beats me to it!

**Comment by jstrachan** [comment]
Am just testing an updated release to gofabric8 that creates cd-pipeline by default (and fixes the bug in the non-creation of the secret namespace for gogs); then folks can use `--app=` to disable starting that app in `gofabric8`. Fingers crossed!

**Comment by jstrachan** [comment]
I'm gonna mark this as fixed as I think we're in good shape now that gofabric8 installs cd-pipeline by default. e.g. here's the getting started instructions for funktion...
https://github.com/fabric8io/funktion#using-the-fabric8-microservices-platform
