### ISSUE TITLE
easy way to delete testing/staging namespaces?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-console#181]
on the new nice Team page; there's no way to delete the testing / staging repos. Sometimes thats a really handy way to just zap the testing stuff to reduce resource usage

**Comment by gashcrumb** [comment]
Yeah, I was wondering if those should be easy to delete or not?  Right now you delete the 'team' which basically downgrades all those to plain old namespaces, you can then delete away...

I guess, maybe we need an extra bit of config to mark a namespace that's an environment as something that can be deleted or not, I think most folks would prefer it if 'production' environments were a little more difficult to get rid of :-)

**Comment by jstrachan** [comment]
I don't want to delete the team; just one of the environment namespaces from a team. e.g. if I wanna clear up all the testing resources; I just wanna delete `default-testing` the Testing environment. I'm never gonna wanna delete the team really (that requires re-installing fabric8 right now)

**Comment by jstrachan** [comment]
We know if its a team or not - the first namespace is the Team Dashboard (its even got a different link) - its the others that should maybe have a delete option or something?

**Comment by jstrachan** [comment]
<img width="692" alt="delete-envs" src="https://cloud.githubusercontent.com/assets/30140/16305959/f6f840f6-3953-11e6-8375-4b0662041447.png">

here's the 2 namespaces I'd like to be able to delete (one or the other really)

**Comment by gashcrumb** [comment]
Also took out that TODO for a create button...
