### ISSUE TITLE
Add spinner in the forge view

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#188]
As its slow to show some content. And there is no spinner so you may think the web page is dead or something.

We have a spinner in the camel view.

![screen shot 2016-07-06 at 11 53 37 am](https://cloud.githubusercontent.com/assets/477100/16614251/67efb30e-4370-11e6-9154-b111f2d8f649.png)

**Comment by gashcrumb** [comment]
+1 for sure,if you're not already working on it I assign it to me...

**Comment by davsclaus** [comment]
Thanks Stan

**Comment by gashcrumb** [comment]
Interestingly enough there actually is a spinner, seems though it takes a bit of time either for the browser to render all the markup or to swizzle the response from forge with all the commands.  Would like to update the spinner so it matches the ones used on the dashboard, will have to see if we can speed up the page rendering a bit too.
