### ISSUE TITLE
console doesn't work on minikube

### ISSUE THREAD

**Issue by svefors** [fabric8io/fabric8-console#189]
As per: https://groups.google.com/forum/#!topic/fabric8/b2ZUSTEh04A

**Comment by svefors** [comment]
But I realise now that maybe it is a minikube rather than a fabric console issue?

**Comment by jimmidyson** [comment]
When you say "doesn't work", do you mean doesn't deploy?

**Comment by svefors** [comment]
No, it deploys and it is there.

when navigating in a browser:
http://<NODE>:<NODEPORT>/workspaces?q=
it will display a message: "There are no teams currently available"

I see a lot of websocket errors in the browser javascript console:
WebSocket connection to 'ws://xhyve.mk:30091/apis/extensions/v1beta1/namespaces/default/deployments?watch=true&access_token' failed: Error during WebSocket handshake: Unexpected response code: 200

**Comment by svefors** [comment]
hmm I guess I shouldn't be accessing the console through the NodePort? The fabric console is trying to connect to the kubernetes API using the same NodePort.

**Comment by jstrachan** [comment]
The console doesn't yet work via the nodePort on kubernetes. It does on OpenShift using its OAuth but on kubernetes, there's no automatic way to inject the authentication token when accessing the underlying REST API.

It can be accessed on kubernetes via the `/api/v1/proxy/namespaces/default/services/fabric8/` API when there is basic auth available on service proxy REST APIs; which is fine on some local kubernetes installations like our vagrant image or on GKE.

However on minikube there's no way to use basic auth to access the REST API; so we can't use that approach to use the console.

I've got a local build working for the console on kubernetes using kuisp to proxy REST calls and add the authentication token; the main issue is lack of websocket support which reduces greatly the user experience and liveness; so I'm reluctant to commit it (and reduce the UX of all kubernetes installations) until we can figure out the websocket proxying issue in kuisp. (Which is happening in this branch if anyone's interested in helping ;) https://github.com/jstrachan/kuisp/tree/websocket)

**Comment by jstrachan** [comment]
this is now fixed by deleting the `fabric8` ReplicationController and re-running `gofabric8`. It should now work fine in minikube too!

I've added instructions on how to do this here: http://fabric8.io/guide/getStarted/minikube.html
