### ISSUE TITLE
Icon for Deployments are not working

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#215]
I started a new minishift with fabric8 (without ci/cd, eg --app=) and in the console the deployments show no icon for expose controller

![screen shot 2016-09-08 at 9 38 33 am](https://cloud.githubusercontent.com/assets/477100/18340983/21b4e048-75a8-11e6-9b57-93fdc2ac427e.png)

**Comment by rawlingsj** [comment]
Are the others icons working?  I think that might just be that there's no icon for the exposecontroller.

I couldn't come up with a good icon, any ideas?  I did start to go down the line of 'the exposecontroller - its likes to expose things' but then thought better of it!

![81036340](https://cloud.githubusercontent.com/assets/1457180/18341352/81fd6d50-75a1-11e6-8b8f-b0fadac02efd.jpg)

On a serious note, if you do have any ideas of a decent icon it would be great.

**Comment by gashcrumb** [comment]
I was seriously considering posting the same icon :-). Lemme see if I can
brainstorm something less racy :-)

**Comment by rawlingsj** [comment]
well at least it would get attention with that icon ;)

**Comment by jstrachan** [comment]
wonder if we should use that icon for exposecontroller :) 

BTW think the icons are all working now - and have added one for exposecontroller
