### ISSUE TITLE
sometimes the gulp build's generated fabric-console.js does not include any Forge plugins JavaScript!

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-console#22]
I've seen this come and go locally and I've no idea why. When there's no JS for the Forge plugin then the CreateProject wizard doesn't do anything. Very odd!

It just seems to come and go randomly locally; restarting gulp seems to fix it again eventually

**Comment by gashcrumb** [comment]
We need to fix the ci job to do a build too, usual reason to not get js is compile errors, but with the ci job not doing a compile it's easy to accidentally release new versions without even rebuilding.

Plus there's too many gulp site runs in that job anyways...

**Comment by gashcrumb** [comment]
I think this is all set?
