### ISSUE TITLE
running cd-pipeline from the console Run.. UI never seems to create 2 PVCs for jenkins-jobs and nexus-storage

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-console#224]
So from the latest gofabric8:
```
gofabric8 start --minishift --console
```
then in the console run `cd-pipeline`.

I always get spinning circles for the creation of `jenkins-jobs` and `nexus-storage` - yet all other resources are created OK (apart from Secret gogs-https-admin which is already there).

Don't see any logs in the console or failed network requests. These 2 PVCs seem to get ignored by the code completely - wacky!!! :)

**Comment by gashcrumb** [comment]
Why do I feel like I fixed this once already?  Lemme give it a go here...

**Comment by gashcrumb** [comment]
BTW this on minishift or minikube?

**Comment by jstrachan** [comment]
I was kinda confused why exactly 2 of the 4 PVCs had this issue - and always those 2. When all other resources work prefectly :) 

This is minishift (the clue is the gofabric8 start --minishift --console) ;)

**Comment by gashcrumb** [comment]
doh, k :-)

**Comment by gashcrumb** [comment]
Interesting, yeah must be some other bug in how the code is applying those...

**Comment by gashcrumb** [comment]
As it turns out, the console was applying all the objects in a tight loop which I was originally trying to avoid.  [Fixed](https://github.com/hawtio/hawtio-kubernetes/commit/1430885d1c441446719c9aaa79ac0e2393b09292) that and I think it works fine now.

**Comment by jstrachan** [comment]
awesome thanks!
