### ISSUE TITLE
Console does not have any contents. 

### ISSUE THREAD

**Issue by magick93** [fabric8io/fabric8-console#256]
I have just done a fresh install of Fabric8 on OpenShift, but the console page loads without any options.

![image](https://cloud.githubusercontent.com/assets/2173213/22185638/bb0c88de-e0e9-11e6-826b-18604391e879.png)
![image](https://cloud.githubusercontent.com/assets/2173213/22185642/c708f794-e0e9-11e6-9869-9ed979aba7f3.png)

Perhaps this is also relevant: 
I created an OpenShift route to the console. 
I'm also unable to open console using
gofabric8 console

When I try I get the same issue as described on https://github.com/fabric8io/fabric8/issues/6725.

**Comment by rawlingsj** [comment]
Did you follow the getting started on openshift guide?  I wonder if you're missing the openshift roles?

Also you shouldn't need to create an routes as the exposecontroller should do that for you.  Is that pod running?  There was a similar issue on a mailing list and I think all that was needed was to include your domain when running gofabric8 deploy on openshift.

e.g.

gofabric8 deploy -d example.fabric8.io

http://fabric8.io/guide/getStarted/openshift.html#getting-started-with-openshift

**Comment by magick93** [comment]
Hi James,

Yes, we followed the directions. 
We reinstalled Fabric8 and I cannot say if it fixed this issue as we are now unable to login - https://github.com/fabric8io/fabric8-console/issues/257
