### ISSUE TITLE
Cant login - redirected to login

### ISSUE THREAD

**Issue by magick93** [fabric8io/fabric8-console#257]
OpenShift Master: v1.4.1+3f9807a
Kubernetes Master: v1.4.0+776c994
gofabric8, version 0.4.113 (branch: 'master', revision: '0610f51')
  build date:       '20170110-20:02:39'
  go version:       '1.7.1'

```
$ gofabric8 validate
             ▄▄▄▄▄▄▄         
             ███████         
     ▄▄▄▄▄▄▄ ▄▄▄▄▄▄█         
     ███████ ▀▀▀▀▀▀▀ ▄▄▄▄▄▄  
     ▄▄▄▄▄▄▄         ██████  
   ▄▄▄▄▄             ▄▄▄▄▄▄  
   ▀▄▄▄▄▄      ▄▄▄       ▄▄▄ 
    ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▀
      ▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█▄▄▀ 
        ▀▀▄█▄▄▄▄▄▄▄▄▄▄▄▄▄▀   
          ▄█▄▄▄█▄▄▄█▄▄▄      
          ▄█▄▄▄▄▄▄▄▄▄▄▄      
           ▄▄█▄▄▄▄▄▄▄▄       
            ▄▄▄▄▀▀▄█▄        
         ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄     
         ▀▀▀▀▀▀▀▀▀▀▀▀▀▀      
Validating your OpenShift installation at https://openshift.myco.com:8443 in namespace default

Service account...............................................................✔ 
Console.......................................................................✔ 
Templates.....................................................................✔ 
SecurityContextConstraints....................................................✔ 
PersistentVolumeClaims........................................................✔ 
ConfigMaps....................................................................✔
```

When trying to view the fabric8 console, the login page displays.
Upon entering correct credentials the login page redirects back to itself.
The outcome is user cannot login and view f8 console.

**Comment by rawlingsj** [comment]
Can you check to see if a fabric8 oauthclient has been created?  i.e. 
```
oc get oauthclient fabric8 -o yaml
```
and check that there is a fabric8 console redirect URL that includes your domain, for example:
```
redirectURIs:
- http://fabric8.demo.example.fabric8.io
```

**Comment by magick93** [comment]
```
$ oc get oauthclient fabric8 -o yaml
apiVersion: v1
kind: OAuthClient
metadata:
  annotations:
    maven.fabric8.io/source-url: jar:file:/root/.mvnrepo/io/fabric8/platform/console/fabric8-console/2.2.199/fabric8-console-2.2.199.jar!/META-INF/fabric8/openshift.yml
  creationTimestamp: 2017-02-02T15:13:39Z
  labels:
    expose: "true"
    group: io.fabric8.apps
    project: fabric8-console
    provider: fabric8
    version: 2.2.199
  name: fabric8
  resourceVersion: "256395"
  selfLink: /oapi/v1/oauthclients/fabric8
  uid: 2d6da3ac-e95a-11e6-90ce-406186becd9d
redirectURIs:
- http://localhost:9000
- http://localhost:9090
- http://localhost:2772
- http://fabric8.default.openshift.mydomain.com

```

**Comment by magick93** [comment]
This is the url:

`https://openshift.myco.com:8443/login?then=%2Foauth%2Fauthorize%3Fclient_id%3Dfabric8%26response_type%3Dtoken%26state%3Dhttp%253A%252F%252Ffabric8.default.openshift.myco.com%252F%253Fscope%253Duser%25253Afull%2526state%253Dhttp%25253A%25252F%25252Ffabric8.default.openshift.myco.com%25252F%26redirect_uri%3Dhttp%253A%252F%252Ffabric8.default.openshift.myco.com%252F%253Fscope%253Duser%25253Afull%2526state%253Dhttp%25253A%25252F%25252Ffabric8.default.openshift.myco.com%25252F`

**Comment by rawlingsj** [comment]
Are there any errors in the browser java script console?

Also are you able to log into the openshift console? https://openshift.myco.com:8443/console

**Comment by magick93** [comment]
> Are there any errors in the browser java script console?

No

> Also are you able to log into the openshift console? https://openshift.myco.com:8443/console

Yes, no problems.

**Comment by rawlingsj** [comment]
>  redirectURIs:
> - http://localhost:9000
> - http://localhost:9090
> - http://localhost:2772
> - http://fabric8.default.openshift.mydomain.com
> It has the correct redirects, from what I can tell.

Is the redirect URL above from your previous comment the exact same as the hostname from the fabric8 route when you run `oc get route fabric8`?

**Comment by magick93** [comment]
Yes
```
$ oc get route fabric8
NAME      HOST/PORT                                 PATH      SERVICES   PORT      TERMINATION
fabric8   fabric8.default.openshift.mydomain.com             fabric8    <all>     
```

**Comment by jstrachan** [comment]
Did you configure your openshift cluster with cors enabled? It's a CLI
argument to 'oc start'

**Comment by rawlingsj** [comment]
There's a section in the getting started with openshift guide that helps with this https://fabric8.io/guide/getStarted/openshift.html#troubleshooting

**Comment by magick93** [comment]
Thanks! @rawlingsj - this was the solution!

**Comment by karstengresch** [comment]
@magick93 - would be great if you could share how you solved the problem...!

**Comment by magick93** [comment]
I followed https://fabric8.io/guide/getStarted/ocClusterUp.html > Extra setup

**Comment by SacDin** [comment]
Hello, 
Having this same issue but on kubernetes
How to solve ?
