### ISSUE TITLE
Now you see it, now you don't!

### ISSUE THREAD

**Issue by tdcox** [fabric8io/fabric8-console#29]
The list of namespaces in the console appears for a second, then vanishes to be replaced by the message "There are no namespaces currently available."
You can see them for a second if you refresh.

**Comment by jstrachan** [comment]
I think this is fixed now isn't it? we now do a regular HTTP query which is fast then do the longer websocket watch (which can sometimes take a little while to set them all up and get data back)

**Comment by davsclaus** [comment]
Yeah I haven't seen namespace flicker anymore recently.
