### ISSUE TITLE
Re-add apiman-manager-ui when it supports minification

### ISSUE THREAD

**Issue by gashcrumb** [fabric8io/fabric8-console#3]
Currently apiman-manager-ui can't be minified as it either declares or uses modules that don't have annotated controllers/directives.  I've temporarily disabled it until we can get that taken care of.

FYI @KurtStam the controller declarations in apiman-manager-ui need to be annotated, more info -> https://scotch.io/tutorials/declaring-angularjs-modules-for-minification

could maybe just run ng-annotate on the generated .js file after compiling the typescript perhaps?

**Comment by EricWittmann** [comment]
https://issues.jboss.org/browse/APIMAN-456

**Comment by EricWittmann** [comment]
OK I think I fixed up the few spots where this was a problem.  The v1.1.3 bower component version of the apiman UI should be OK to minify.  If it still fails, and you can tell me specifically where, that'd be super helpful. :)

**Comment by gashcrumb** [comment]
This is all set

**Comment by rawlingsj** [comment]
[merge]
