### ISSUE TITLE
Add a way of getting the version of the web console

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#4]
Hi @gashcrumb it would be great if there was a way of easy get the version of the console.

In 1.x we had an "About" menu. 

eg it would also help you when reporting issues that we know from which version it is.

**Comment by davsclaus** [comment]
Also maybe if the fabric-console docker image and whatever is used as http server could maybe do some kind of logging of that. All I see is

```
davsclaus:~/workspace/fabric8 (master)/$ docker logs c08799130b62
2015/06/07 09:19:53 Creating config file:  /site/osconsole/config.js.tmpl => /site/osconsole/config.js
2015/06/07 09:19:53
2015/06/07 09:19:53 Listening on :9090
2015/06/07 09:19:53
```

Where c08799130b62 is the container id of the fabric8-console

**Comment by gashcrumb** [comment]
Oh, forgot to update this, I've added 'about' pages to the preferences in fabric8-console and also openshift-jvm which lists the console version and all the dependency versions, so it's at least available in the console itself.
