### ISSUE TITLE
Stuck when not selecting namespace.

### ISSUE THREAD

**Issue by rafabene** [fabric8io/fabric8-console#59]
I have installed CD-Pipeline installed but when I try to run it but without selecting a workspace, I get stuck on "You are not running the CD Pipeline application in this workspace." - I shouldn't be allowed to click the +Create button without selecting a workspace.

Screencast: http://screencast.com/t/3512X0xA4

**Comment by jstrachan** [comment]
fixed by the working `Create Namespace` button
