### ISSUE TITLE
Can't go after Set the Gogs secret

### ISSUE THREAD

**Issue by rafabene** [fabric8io/fabric8-console#61]
I selected the workspace and then it asked me to to setup a gogs secret. I created a secret but I can proceed.

Screencast: http://screencast.com/t/gd11Ibxo

**Comment by jstrachan** [comment]
I've polished the UI to make it more clear by improving the button text and adding a warning text to inform the user what they need to do next. 

e.g. after creating but not selecting a secret:
<img width="1137" alt="no-selection" src="https://cloud.githubusercontent.com/assets/30140/11952122/0799f384-a88e-11e5-86f4-eff1bf06b2ee.png">

then after selecting but not saving a selection:
<img width="1137" alt="notsaved" src="https://cloud.githubusercontent.com/assets/30140/11952136/1eceddd0-a88e-11e5-9e63-46875be2ea6b.png">
