### ISSUE TITLE
Overview - Can the arrows be aligned to the center of the box

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-console#89]
The overview page the arrows is a bit confusing to spot, because they are lined from the top corner of the boxes.

Can they be moved to the center of the box instead?

![screen shot 2016-02-03 at 10 21 57 am](https://cloud.githubusercontent.com/assets/477100/12777942/187881fe-ca60-11e5-87ef-17958c23fa5b.png)

**Comment by davsclaus** [comment]
eg the boxes on the right hand side, eg so the 9200 ES box the arrow was from the middle.

**Comment by davsclaus** [comment]
@gashcrumb a few fun overview issues logged. Thanks btw for making it useable again.

**Comment by gashcrumb** [comment]
Have this one fixed, now the jsplumb directive will ensure that the element it's on is position:relative which should sort these types of issues.
